/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_HelloJNI */

#ifndef _Included_myjni_HelloJNI
#define _Included_myjni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloJNI
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJNI_modifyInstanceVariable
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloJNI
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJNI_modifyStaticVariable
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloJNI
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJNI_nativeMethod
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloJNI
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_myjni_HelloJNI_getIntegerObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     myjni_HelloJNI
 * Method:    sumAndAverage
 * Signature: ([Ljava/lang/Integer;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_myjni_HelloJNI_sumAndAverage
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     myjni_HelloJNI
 * Method:    getIntegerXxxObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_myjni_HelloJNI_getIntegerXxxObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     myjni_HelloJNI
 * Method:    anotherGetIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_myjni_HelloJNI_anotherGetIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
