/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_HelloJNI */

#ifndef _Included_myjni_HelloJNI
#define _Included_myjni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloJNI
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJNI_modifyInstanceVariable
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloJNI
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJNI_modifyStaticVariable
  (JNIEnv *, jobject);



JNIEXPORT void JNICALL Java_myjni_HelloJNI_nativeMethod
(JNIEnv *env, jobject thisObj);

JNIEXPORT jobject JNICALL Java_myjni_HelloJNI_getIntegerObject
(JNIEnv *env, jobject thisObj, jint number);

JNIEXPORT jobjectArray JNICALL Java_myjni_HelloJNI_sumAndAverage
(JNIEnv *env, jobject thisObj, jobjectArray inJNIArray);

JNIEXPORT jobject JNICALL Java_myjni_HelloJNI_getIntegerXxxObject
(JNIEnv *env, jobject thisObj, jint number);

JNIEXPORT jobject JNICALL Java_myjni_HelloJNI_anotherGetIntegerObject
(JNIEnv *env, jobject thisObj, jint number);

#ifdef __cplusplus
}
#endif
#endif
